name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - matplotlib==3.9.2
  - numpy==2.1.2
  - pyvista==0.44.2
  - PyYAML==6.0
  - scipy==1.14.1
  - trame
  - trame-vtk
  - pyvista[jupyter]
  - jupyterlab==4.3.5
