name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - astropy==6.1.4
  - astroquery==0.4.7
  - matplotlib==3.9.2
  - numpy==2.1.2
  - pandas==2.2.3
  - pyspeckit==1.0.3
  - pyvista==0.44.2
  - PyYAML==6.0
  - scipy==1.14.1
  - seaborn==0.13.2
  - spectral-cube==0.6.5
  - trame
  - trame-vtk
  - pyvista[jupyter]
  - jupyter-contrib-core==0.4.2
  - jupyter-contrib-nbextensions==0.7.0
  - jupyter-events==0.11.0
  - jupyter-highlight-selected-word==0.2.0
  - jupyter-lsp==2.2.5
  - jupyter_client==8.6.3
  - jupyter_core==5.7.2
  - jupyter_nbextensions_configurator==0.6.4
  - jupyter_server==2.15.0
  - jupyter_server_proxy==4.4.0
  - jupyter_server_terminals==0.5.3
  - jupyterlab==4.3.5
  - jupyterlab_pygments==0.3.0
  - jupyterlab_server==2.27.3
  - jupyterlab_widgets==3.0.13
